version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'sync'
    open-pull-requests-limit: 5
    target-branch: 'main'
    source:
      repo: 'kode-krew/meta-test-be'
      branch: 'main'
